[package]
name = "rustaddin"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
jni = { version = "0.21.1", features = ["invocation"] }
glob = "0.3.1"
shell-words = "1.0.0"
anyhow = "1.0.79"

[profile.release]
lto = true